### ISSUE TITLE
VRChat SDK update broke functionality 

### ISSUE THREAD

**Issue by TealOrangeCat** [Miner28/NetworkedEventCaller#1]
Hi!
Updating to the newest SDK (VRCWorlds and UdonSharp) gives this error:

[UdonSharp] Assets/Miner28/NetworkedEventCaller/Scripts/NetworkedEventCaller.cs(32,34): Cannot sync type 'Types[]'

**Comment by Miner28** [comment]
Move back to older u# SDK temporarily it will be fixed it new u# version.

**Comment by Miner28** [comment]
Fixed in U# 1.1.5
