### ISSUE TITLE
Outdated listing

### ISSUE THREAD

**Issue by MagmaVRC** [Miner28/NetworkedEventCaller#6]
your latest versions of this package has not been listed, you will need to go re-run the action "Build Repo Listing" on your "MinerPackages" repo

**Comment by Miner28** [comment]
Ah 🤔 I've just ran the listing but it still didn't update lol, gonna have to figure out what's going on but thanks for letting me know!

**Comment by Miner28** [comment]
Oh, ok nvm I just had to Force-reload with Shift+F5 xD 

Thanks again, updated now!
